# vim: set ft=yaml ts=2:
---

- name: assertions
  assert:
    that:
      - ansible_distribution == 'CentOS'
      - ansible_distribution_major_version|int == 7

- name: kibana is present
  package:
    name: kibana
    state: present

- name: kibana is configured
  template:
    src: kibana.yml.j2
    dest: /etc/kibana/kibana.yml
    backup: true

  notify: reload kibana
- name: kibana is started
  service:
    name: kibana
    state: started
    enabled: true
